// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ReadProperties():Promise<Array<main.PropertiesData>>;

export function Save(arg1:Array<main.PropertiesData>):Promise<void>;
